version: "3.8"

services:
  stratum-db:
    image: postgres:15.3
    container_name: talents-db
    restart: always
    ports:
      - 5434:5432 # I used the port 5434 beceause i'm using 5432 :)
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./talents-postgres-data:/var/lib/postgresql/data
